import { SkillCode } from "../types/skills.d.ts";

export const SKILL_MAP: Record<SkillCode, string> = {
  COD: "Coding",
  DBM: "Databases",
  MAT: "Mathematics",
  SEC: "Cybersecurity",
  AI: "AI Training",
  DES: "Design",
  CPY: "Copywriting",
  VID: "Video Production",
  MKT: "Marketing",
  NEG: "Negotiation",
  PRJ: "Project Management",
  FIN: "Finance",
  ENG: "Professional Writing",
  PUB: "Public Speaking",
  NET: "Networking",
};
export const GLOBAL_STATUS = [
  {
    min: 0,
    max: 50,
    title: "Aspiring Freelancer",
    tag: "Getting Started",
  },
  {
    min: 50,
    max: 100,
    title: "Rising Professional",
    tag: "Building Momentum",
  },
  {
    min: 100,
    max: 200,
    title: "Established Expert",
    tag: "Trusted Name",
  },
  {
    min: 200,
    max: 400,
    title: "Industry Authority",
    tag: "High Demand",
  },
  {
    min: 400,
    max: Infinity,
    title: "Global Icon",
    tag: "Legendary Status",
  },
];

// 1. Define Tier-Specific Task Pools
export const GIG_POOLS: Record<string, { title: string; skill: string }[]> = {
  small: [
    { title: "Fix broken checkout button.", skill: "COD" },
    { title: "Set up simple 1-page website.", skill: "COD" },
    { title: "Clean duplicate database entries.", skill: "DBM" },
    { title: "Connect site to REST API.", skill: "COD" },
    { title: "Write 300-word landing copy.", skill: "CPY" },
    { title: "Design simple business logo.", skill: "DES" },
    { title: "Create Instagram post graphic.", skill: "DES" },
    { title: "Design promotional flyer.", skill: "DES" },
    { title: "Create YouTube thumbnail.", skill: "DES" },
    { title: "Edit 5-minute video.", skill: "VID" },
    { title: "Input spreadsheet data (200 rows).", skill: "PRJ" },
    { title: "Fix Excel formula errors.", skill: "MAT" },
    { title: "Set up support email inbox.", skill: "PRJ" },
    { title: "Import contacts to CRM.", skill: "PRJ" },
    { title: "Create invoice template.", skill: "FIN" },
    { title: "Optimize blog post for SEO.", skill: "MKT" },
    { title: "Design email newsletter layout.", skill: "MKT" },
    { title: "Write Facebook ad copy.", skill: "CPY" },
    { title: "Rewrite resume professionally.", skill: "ENG" },
    { title: "Proofread 1,000-word article.", skill: "ENG" },
    { title: "Resize 20 product images.", skill: "DES" },
    { title: "Remove image background.", skill: "DES" },
    { title: "Install Google Analytics.", skill: "MKT" },
    { title: "Fix CSS alignment issue.", skill: "COD" },
    { title: "Convert PDF to Word document.", skill: "PRJ" },
    { title: "Create Google Form survey.", skill: "PRJ" },
    { title: "Add captions to short video.", skill: "VID" },
    { title: "Write product description.", skill: "CPY" },
    { title: "Test mobile responsiveness.", skill: "COD" },
    { title: "Research 50 business leads.", skill: "PRJ" },
    { title: "Set up Calendly booking link.", skill: "PRJ" },
    { title: "Format PowerPoint slides.", skill: "DES" },
    { title: "Basic WordPress plugin update.", skill: "COD" },
    { title: "Transcribe 10-minute audio.", skill: "ENG" },
    { title: "Create simple Excel chart.", skill: "MAT" },
    { title: "Schedule social media posts.", skill: "MKT" },
    { title: "Fix website broken links.", skill: "COD" },
    { title: "Design basic banner ad.", skill: "DES" },
    { title: "Organize Google Drive folders.", skill: "PRJ" },
    { title: "Write short blog introduction.", skill: "CPY" },
    { title: "Set up Zoom meeting system.", skill: "PRJ" },
    { title: "Create basic contact form.", skill: "COD" },
    { title: "Do keyword research for 5 terms.", skill: "MKT" },
    { title: "Edit podcast intro.", skill: "VID" },
    { title: "Prepare simple budget sheet.", skill: "FIN" },
    { title: "Fix website footer layout.", skill: "COD" },
    { title: "Create LinkedIn company page.", skill: "MKT" },
    { title: "Clean email subscriber list.", skill: "PRJ" },
    { title: "Design simple business card.", skill: "DES" },
    { title: "Write professional bio.", skill: "CPY" },
  ],
  medium: [
    { title: "Build responsive landing page.", skill: "COD" },
    { title: "Set up full WordPress website.", skill: "COD" },
    { title: "Design custom dashboard UI.", skill: "DES" },
    { title: "Integrate Stripe payments.", skill: "COD" },
    { title: "Develop workflow automation.", skill: "COD" },
    { title: "Create full brand style guide.", skill: "DES" },
    { title: "Launch social media campaign.", skill: "MKT" },
    { title: "Design investor pitch deck.", skill: "DES" },
    { title: "Optimize website speed.", skill: "COD" },
    { title: "Produce explainer video.", skill: "VID" },
    { title: "Set up Google Ads campaign.", skill: "MKT" },
    { title: "Write press release.", skill: "CPY" },
    { title: "Develop booking system.", skill: "COD" },
    { title: "Create inventory tracker.", skill: "PRJ" },
    { title: "Implement CRM automation.", skill: "PRJ" },
    { title: "Create financial report template.", skill: "FIN" },
    { title: "Customize Shopify theme.", skill: "COD" },
    { title: "Run SEO audit.", skill: "MKT" },
    { title: "Write detailed case study.", skill: "CPY" },
    { title: "Optimize SQL performance.", skill: "DBM" },
    { title: "Build Excel dashboard.", skill: "MAT" },
    { title: "Create email automation funnel.", skill: "MKT" },
    { title: "Design product packaging.", skill: "DES" },
    { title: "Develop REST API backend.", skill: "COD" },
    { title: "Create marketing funnel.", skill: "MKT" },
    { title: "Edit full podcast episode.", skill: "VID" },
    { title: "Draft service agreement.", skill: "ENG" },
    { title: "Set up affiliate program.", skill: "MKT" },
    { title: "Migrate website hosting.", skill: "COD" },
    { title: "Design interactive prototype.", skill: "DES" },
    { title: "Analyze survey results.", skill: "MAT" },
    { title: "Develop internal dashboard.", skill: "COD" },
    { title: "Build customer portal.", skill: "COD" },
    { title: "Set up email marketing system.", skill: "MKT" },
    { title: "Implement analytics tracking.", skill: "COD" },
    { title: "Create onboarding workflow.", skill: "PRJ" },
    { title: "Design multi-page brochure.", skill: "DES" },
    { title: "Improve database indexing.", skill: "DBM" },
    { title: "Create lead generation campaign.", skill: "MKT" },
    { title: "Write long-form blog post.", skill: "CPY" },
    { title: "Develop simple mobile app.", skill: "COD" },
    { title: "Prepare business financial summary.", skill: "FIN" },
    { title: "Conduct competitor analysis.", skill: "MKT" },
    { title: "Implement role-based access.", skill: "COD" },
    { title: "Build event registration system.", skill: "COD" },
    { title: "Design social media templates.", skill: "DES" },
    { title: "Create data visualization report.", skill: "MAT" },
    { title: "Set up cloud hosting server.", skill: "COD" },
    { title: "Draft privacy policy document.", skill: "ENG" },
    { title: "Build subscription management.", skill: "COD" },
  ],
  startup: [
    { title: "Build full e-commerce platform.", skill: "COD" },
    { title: "Design complete mobile app UI/UX.", skill: "DES" },
    { title: "Develop scalable backend API.", skill: "COD" },
    { title: "Build SaaS MVP.", skill: "COD" },
    { title: "Create analytics dashboard system.", skill: "MAT" },
    { title: "Implement subscription billing.", skill: "COD" },
    { title: "Develop online marketplace.", skill: "COD" },
    { title: "Create full SEO growth plan.", skill: "MKT" },
    { title: "Design brand identity system.", skill: "DES" },
    { title: "Manage multi-channel ads.", skill: "MKT" },
    { title: "Build financial forecasting model.", skill: "FIN" },
    { title: "Prepare investor pitch deck.", skill: "FIN" },
    { title: "Migrate infra to AWS.", skill: "COD" },
    { title: "Build React Native app.", skill: "COD" },
    { title: "Develop ML recommendation system.", skill: "AI" },
    { title: "Implement database scaling.", skill: "DBM" },
    { title: "Build real-time messaging.", skill: "COD" },
    { title: "Create trading bot system.", skill: "COD" },
    { title: "Develop internal admin tools.", skill: "PRJ" },
    { title: "Produce product launch campaign.", skill: "MKT" },
    { title: "Implement advanced security system.", skill: "SEC" },
    { title: "Create SaaS onboarding flow.", skill: "PRJ" },
    { title: "Design gamified user experience.", skill: "DES" },
    { title: "Optimize backend performance.", skill: "COD" },
    { title: "Build centralized data warehouse.", skill: "DBM" },
    { title: "Launch influencer campaign.", skill: "MKT" },
    { title: "Implement predictive sales model.", skill: "MAT" },
    { title: "Develop compliance framework.", skill: "ENG" },
    { title: "Build custom CRM.", skill: "COD" },
    { title: "Scale server capacity.", skill: "COD" },
    { title: "Develop mobile payment integration.", skill: "COD" },
    { title: "Create customer loyalty system.", skill: "PRJ" },
    { title: "Build AI chatbot assistant.", skill: "AI" },
    { title: "Design enterprise dashboard.", skill: "DES" },
    { title: "Automate business operations.", skill: "PRJ" },
    { title: "Develop API gateway system.", skill: "COD" },
    { title: "Create investor reporting dashboard.", skill: "FIN" },
    { title: "Optimize cloud cost structure.", skill: "FIN" },
    { title: "Develop analytics tracking pipeline.", skill: "MAT" },
    { title: "Launch global SaaS beta.", skill: "COD" },
    { title: "Build B2B client portal.", skill: "COD" },
    { title: "Implement zero-trust security.", skill: "SEC" },
    { title: "Create automated CI/CD pipeline.", skill: "COD" },
    { title: "Develop marketplace escrow system.", skill: "FIN" },
    { title: "Build subscription analytics tool.", skill: "MAT" },
    { title: "Create digital onboarding academy.", skill: "PRJ" },
    { title: "Design scalable design system.", skill: "DES" },
    { title: "Develop AI data classification.", skill: "AI" },
    { title: "Implement SaaS billing analytics.", skill: "FIN" },
    { title: "Build internal knowledge base.", skill: "PRJ" },
  ],

  national: [
    { title: "Deploy AI fraud detection system nationwide.", skill: "AI" },
    {
      title: "Design scalable SaaS architecture for millions of users.",
      skill: "COD",
    },
    { title: "Implement multi-region cloud infrastructure.", skill: "COD" },
    { title: "Conduct nationwide cybersecurity audit.", skill: "SEC" },
    {
      title: "Implement enterprise ERP system across company branches.",
      skill: "PRJ",
    },
    { title: "Build enterprise mobile banking application.", skill: "COD" },
    {
      title: "Design microservices architecture for enterprise system.",
      skill: "COD",
    },
    { title: "Integrate blockchain for supply chain tracking.", skill: "COD" },
    { title: "Create national digital transformation roadmap.", skill: "PRJ" },
    { title: "Perform large-scale M&A financial analysis.", skill: "FIN" },

    { title: "Build hospital management system network.", skill: "COD" },
    { title: "Launch nationwide telemedicine platform.", skill: "COD" },
    { title: "Develop enterprise fraud monitoring engine.", skill: "SEC" },
    { title: "Create smart city traffic management platform.", skill: "COD" },
    { title: "Design enterprise financial modeling suite.", skill: "FIN" },
    { title: "Deploy company-wide encryption system.", skill: "SEC" },
    { title: "Build nationwide logistics management platform.", skill: "PRJ" },
    { title: "Develop large-scale AI recommendation system.", skill: "AI" },
    { title: "Launch national TV & digital marketing campaign.", skill: "MKT" },
    { title: "Develop autonomous vehicle vision AI prototype.", skill: "AI" },

    { title: "Build core banking software system.", skill: "COD" },
    { title: "Create AI-powered credit scoring system.", skill: "AI" },
    { title: "Design disaster recovery infrastructure.", skill: "COD" },
    { title: "Implement enterprise data lake architecture.", skill: "DBM" },
    { title: "Conduct IPO readiness audit.", skill: "FIN" },
    { title: "Develop telecom billing infrastructure.", skill: "COD" },
    { title: "Design corporate rebranding strategy nationwide.", skill: "DES" },
    { title: "Implement end-to-end encryption rollout.", skill: "SEC" },
    { title: "Build government digital services portal.", skill: "COD" },
    { title: "Develop enterprise HR management system.", skill: "PRJ" },

    { title: "Create AI-based medical diagnosis assistant.", skill: "AI" },
    { title: "Modernize legacy banking infrastructure.", skill: "COD" },
    { title: "Build nationwide education LMS platform.", skill: "COD" },
    { title: "Design predictive energy consumption model.", skill: "MAT" },
    { title: "Implement cloud migration for enterprise group.", skill: "COD" },
    { title: "Develop nationwide tax reporting system.", skill: "FIN" },
    { title: "Launch fintech super app.", skill: "COD" },
    { title: "Build AI-driven threat detection platform.", skill: "SEC" },
    { title: "Create enterprise procurement system.", skill: "PRJ" },
    { title: "Develop national e-commerce infrastructure.", skill: "COD" },

    { title: "Implement data privacy compliance system.", skill: "ENG" },
    { title: "Build AI-powered supply forecasting engine.", skill: "AI" },
    { title: "Design scalable API gateway network.", skill: "COD" },
    { title: "Create enterprise analytics reporting hub.", skill: "MAT" },
    { title: "Launch national fintech payment network.", skill: "COD" },
    { title: "Develop biometric authentication system.", skill: "SEC" },
    { title: "Build nationwide property management platform.", skill: "COD" },
    { title: "Implement AI-driven customer support system.", skill: "AI" },
    { title: "Create enterprise SaaS ecosystem platform.", skill: "COD" },
    {
      title: "Develop national infrastructure monitoring system.",
      skill: "COD",
    },
  ],
  global: [
    { title: "Develop global AI infrastructure platform.", skill: "AI" },
    {
      title: "Build international cross-border payment network.",
      skill: "COD",
    },
    { title: "Design planetary-scale cloud infrastructure.", skill: "COD" },
    { title: "Create global cybersecurity defense grid.", skill: "SEC" },
    { title: "Launch worldwide digital currency system.", skill: "COD" },
    { title: "Develop AI climate prediction system.", skill: "AI" },
    { title: "Build global satellite data analytics platform.", skill: "COD" },
    { title: "Create international trade automation system.", skill: "NEG" },
    { title: "Develop global healthcare data exchange.", skill: "COD" },
    { title: "Build worldwide fraud detection AI network.", skill: "AI" },

    {
      title: "Implement global supply chain optimization platform.",
      skill: "PRJ",
    },
    { title: "Build multinational banking infrastructure.", skill: "FIN" },
    { title: "Launch global streaming platform.", skill: "COD" },
    { title: "Develop space telemetry monitoring network.", skill: "DES" },
    { title: "Create worldwide renewable energy grid software.", skill: "COD" },
    {
      title: "Build international AI research consortium platform.",
      skill: "AI",
    },
    { title: "Deploy quantum computing infrastructure network.", skill: "AI" },
    { title: "Develop global autonomous logistics AI.", skill: "AI" },
    { title: "Create universal digital identity system.", skill: "SEC" },
    { title: "Launch worldwide SaaS marketplace ecosystem.", skill: "COD" },

    { title: "Design global fintech infrastructure platform.", skill: "FIN" },
    { title: "Build AI-powered global news platform.", skill: "AI" },
    { title: "Develop universal real-time translation AI.", skill: "AI" },
    { title: "Create worldwide smart city integration network.", skill: "COD" },
    {
      title: "Build multinational compliance automation system.",
      skill: "ENG",
    },
    { title: "Design planetary IoT infrastructure framework.", skill: "COD" },
    {
      title: "Develop AI-powered global defense monitoring system.",
      skill: "SEC",
    },
    {
      title: "Create intercontinental high-speed data exchange.",
      skill: "DBM",
    },
    { title: "Launch worldwide digital governance system.", skill: "PRJ" },
    {
      title: "Build next-generation internet protocol platform.",
      skill: "COD",
    },

    {
      title: "Develop AI-based global economic forecasting engine.",
      skill: "AI",
    },
    {
      title: "Create international blockchain financial network.",
      skill: "COD",
    },
    {
      title: "Build global disaster response coordination platform.",
      skill: "PRJ",
    },
    { title: "Develop worldwide pandemic tracking system.", skill: "AI" },
    {
      title: "Create international AI ethics governance framework.",
      skill: "ENG",
    },
    {
      title: "Launch multinational AI healthcare diagnostics platform.",
      skill: "AI",
    },
    { title: "Build global carbon credit trading system.", skill: "FIN" },
    { title: "Develop AI-powered energy optimization grid.", skill: "AI" },
    {
      title: "Create worldwide autonomous vehicle infrastructure.",
      skill: "AI",
    },
    { title: "Build global satellite internet system.", skill: "COD" },

    {
      title: "Design multinational central banking digital system.",
      skill: "FIN",
    },
    { title: "Develop AI-driven international trade analytics.", skill: "AI" },
    {
      title: "Create worldwide cybersecurity intelligence network.",
      skill: "SEC",
    },
    { title: "Build cross-continental logistics automation AI.", skill: "AI" },
    { title: "Launch global AI-powered education platform.", skill: "AI" },
    { title: "Develop planetary-scale cloud storage platform.", skill: "COD" },
    {
      title: "Create global predictive climate simulation engine.",
      skill: "AI",
    },
    { title: "Build worldwide decentralized identity platform.", skill: "SEC" },
    {
      title: "Develop international real-time financial clearing system.",
      skill: "FIN",
    },
    {
      title: "Create AI-powered global crisis management platform.",
      skill: "AI",
    },
  ],
};
