import { SkillCode } from "../types/skills.d.ts";

export const SKILL_MAP: Record<SkillCode, string> = {
  COD: "Coding",
  DBM: "Databases",
  MAT: "Mathematics",
  SEC: "Cybersecurity",
  AI: "AI Training",
  DES: "Design",
  CPY: "Copywriting",
  VID: "Video Production",
  MKT: "Marketing",
  NEG: "Negotiation",
  PRJ: "Project Management",
  FIN: "Finance",
  ENG: "Professional Writing",
  PUB: "Public Speaking",
  NET: "Networking",
};
export const GLOBAL_STATUS = [
  {
    min: 0,
    max: 50,
    title: "Aspiring Freelancer",
    tag: "Getting Started",
  },
  {
    min: 50,
    max: 100,
    title: "Rising Professional",
    tag: "Building Momentum",
  },
  {
    min: 100,
    max: 200,
    title: "Established Expert",
    tag: "Trusted Name",
  },
  {
    min: 200,
    max: 400,
    title: "Industry Authority",
    tag: "High Demand",
  },
  {
    min: 400,
    max: Infinity,
    title: "Global Icon",
    tag: "Legendary Status",
  },
];

// 1. Define Tier-Specific Task Pools
export const GIG_POOLS: Record<string, { title: string; skill: string }[]> = {
  Bronze: [
    { title: "Small bug in checkout. Can you fix it?", skill: "COD" },
    { title: "Need a basic website setup.", skill: "COD" },
    { title: "Database cleanup needed.", skill: "DBM" },
    { title: "API connection isn’t working.", skill: "COD" },
    { title: "Write short copy for landing page.", skill: "CPY" },
    { title: "Logo for small business.", skill: "DES" },
    { title: "Social post for our brand.", skill: "DES" },
    { title: "Quick flyer design.", skill: "DES" },
    { title: "Thumbnail for video.", skill: "DES" },
    { title: "Basic video editing.", skill: "VID" },
    { title: "Enter data into spreadsheet.", skill: "PRJ" },
    { title: "Fix broken formulas.", skill: "MAT" },
    { title: "Set up customer support inbox.", skill: "PRJ" },
    { title: "Import contacts into CRM.", skill: "PRJ" },
    { title: "Create invoice template.", skill: "FIN" },
    { title: "Do basic SEO.", skill: "MKT" },
    { title: "Help with email newsletter.", skill: "MKT" },
    { title: "Facebook ad copy needed.", skill: "CPY" },
    { title: "Can you rewrite my resume?", skill: "ENG" },
    { title: "Online tutoring help?", skill: "ENG" },
    { title: "Virtual assistant task.", skill: "PRJ" },
  ],

  Silver: [
    { title: "Build a landing page.", skill: "COD" },
    { title: "WordPress setup.", skill: "COD" },
    { title: "Custom dashboard UI.", skill: "DES" },
    { title: "API integration.", skill: "COD" },
    { title: "Automation script.", skill: "COD" },
    { title: "UI kit design.", skill: "DES" },
    { title: "Brand style guide.", skill: "DES" },
    { title: "Social campaign package.", skill: "MKT" },
    { title: "Pitch deck design.", skill: "DES" },
    { title: "Product packaging design.", skill: "DES" },
    { title: "Email campaign setup.", skill: "MKT" },
    { title: "Content strategy plan.", skill: "MKT" },
    { title: "Marketing funnel setup.", skill: "MKT" },
    { title: "SEO optimization.", skill: "MKT" },
    { title: "Bookkeeping setup.", skill: "FIN" },
    { title: "Financial report template.", skill: "FIN" },
    { title: "Contract template draft.", skill: "ENG" },
    { title: "Online course setup.", skill: "PRJ" },
    { title: "Employee onboarding kit.", skill: "PRJ" },
    { title: "Workflow redesign.", skill: "PRJ" },
  ],

  Gold: [
    { title: "E-commerce website build.", skill: "COD" },
    { title: "Mobile app UI design.", skill: "DES" },
    { title: "Custom API development.", skill: "COD" },
    { title: "Automation system.", skill: "COD" },
    { title: "Analytics dashboard.", skill: "MAT" },
    { title: "MVP development.", skill: "COD" },
    { title: "Subscription setup.", skill: "COD" },
    { title: "Marketplace platform.", skill: "COD" },
    { title: "Full SEO strategy.", skill: "MKT" },
    { title: "Brand identity system.", skill: "DES" },
    { title: "Ad campaign management.", skill: "MKT" },
    { title: "Sales funnel optimization.", skill: "MKT" },
    { title: "Financial forecast model.", skill: "FIN" },
    { title: "Pitch deck for investors.", skill: "FIN" },
    { title: "Cost optimization audit.", skill: "FIN" },
    { title: "Business process audit.", skill: "PRJ" },
    { title: "Compliance documentation.", skill: "ENG" },
    { title: "E-learning platform.", skill: "COD" },
    { title: "Podcast production.", skill: "VID" },
    { title: "Clinic system setup.", skill: "COD" },
  ],

  Platinum: [
    { title: "AI integration project.", skill: "AI" },
    { title: "ML model deployment.", skill: "AI" },
    { title: "SaaS architecture design.", skill: "COD" },
    { title: "Cloud infrastructure setup.", skill: "COD" },
    { title: "Cybersecurity audit.", skill: "SEC" },
    { title: "ERP implementation.", skill: "PRJ" },
    { title: "Enterprise mobile app.", skill: "COD" },
    { title: "Microservices architecture.", skill: "COD" },
    { title: "Blockchain integration.", skill: "COD" },
    { title: "Digital transformation plan.", skill: "PRJ" },
    { title: "Global expansion strategy.", skill: "NEG" },
    { title: "Corporate rebranding.", skill: "DES" },
    { title: "M&A analysis.", skill: "FIN" },
    { title: "Enterprise financial modeling.", skill: "FIN" },
    { title: "International tax structure.", skill: "FIN" },
    { title: "Hospital system digitization.", skill: "COD" },
    { title: "Telemedicine platform.", skill: "COD" },
    { title: "Regulatory compliance overhaul.", skill: "ENG" },
    { title: "Global marketing campaign.", skill: "MKT" },
    { title: "Streaming platform launch.", skill: "COD" },
  ],
};
