export const SEED_DATA = [
  `INSERT OR IGNORE INTO daily_milestones (id, name, description, icon, color, target_value, target_type, reward_money, reward_xp) VALUES 
  ('m1', 'Coffee Money', 'Earn your first $50 today', 'payments', '#3b82f6', 50, 'MONEY', 25, 10),
  ('m2', 'Big Leagues', 'Earn a total of $500 today', 'monetization-on','#fbbf24', 500, 'MONEY', 100, 50),
  ('m3', 'Rainmaker', 'Earn a total of $1,000 today', 'trending-up','#ef4444', 1000, 'MONEY', 250, 100),
  ('m4', 'Tax Season', 'Earn $2,500 in a single day', 'account-balance', '#10b981', 2500, 'MONEY', 500, 200),
  ('m5', 'Fast Starter', 'Complete 1 gig', 'bolt', '#f97316', 1, 'GIGS', 20, 30),
  ('m6', 'Busy Bee', 'Complete 3 gigs today', 'work', '#f43f5e', 3, 'GIGS', 100, 75),
  ('m7', 'Workaholic', 'Complete 5 gigs today', 'business-center', '#8b5cf6', 5, 'GIGS', 250, 150),
  ('m8', 'Outsourcer', 'Complete 10 gigs today', 'groups', '#06b6d4', 10, 'GIGS', 600, 400),
  ('m9', 'Self Improvement', 'Gain 100 total XP', 'school', '#6366f1', 100, 'XP', 50, 50),
  ('m10', 'Deep Work', 'Gain 500 total XP', 'psychology', '#a855f7', 500, 'XP', 200, 100),
  ('m11', 'Expertise', 'Level up any skill once', 'star', '#fbbf24', 1, 'SKILL_UP', 300, 200),
  ('m12', 'Polymath', 'Level up 3 different skills', 'auto-awesome', '#f59e0b', 3, 'SKILL_UP', 1000, 500),
  ('m13', 'Rising Star', 'Gain 5 Reputation points', 'thumb-up', '#22c55e', 5, 'REPUTATION', 100, 50),
  ('m14', 'Local Legend', 'Gain 20 Reputation points', 'verified', '#14b8a6', 20, 'REPUTATION', 500, 250),
  ('m15', 'Networking', 'Apply for 5 different gigs', 'send', '#ec4899', 5, 'APPLICATIONS', 50, 20),
  ('m16', 'High Stakes', 'Complete a gig worth over $1000', 'diamond', '#0ea5e9', 1, 'HIGH_VALUE_GIG', 250, 100),
  ('m17', 'Bug Hunter', 'Complete 2 ''Development'' type gigs', 'bug-report', '#3b82f6', 2, 'GIG_TYPE_DEV', 150, 80),
  ('m18', 'Creative Soul', 'Complete 2 ''Design'' type gigs', 'palette', '#fb923c', 2, 'GIG_TYPE_DESIGN', 150, 80),
  ('m19', 'Closer', 'Finish a gig within 1 hour of starting', 'timer', '#ef4444', 1, 'SPEED_FINISH', 200, 100),
  ('m20', 'Overachiever', 'Complete all other 4 dailies', 'workspace-premium', '#ffd700', 4, 'DAILIES_COMPLETED', 1000, 1000);`,

  `INSERT OR IGNORE INTO skills (id, code, name, description, color, icon, category, learn_duration_minutes, base_xp, price, unlock_at) VALUES
  ('s1', 'COD', 'Coding', 'Build software, websites, and automation.', '#3b82f6', 'laptop', 'Technical', 1, 100, 2500, 1),
  ('s2', 'DBM', 'Databases', 'Design and manage data storage systems.', '#06b6d4', 'storage', 'Technical', 15, 110, 2500, 1),
  ('s3', 'MAT', 'Mathematics', 'Logic and analytics for problem solving.', '#6366f1', 'calculate', 'Technical', 15, 120, 2500, 1),
  ('s4', 'SEC', 'Cybersecurity', 'Protect systems and data from threats.', '#ef4444', 'security', 'Technical', 150, 120, 3500, 5),
  ('s5', 'AI', 'AI Training', 'Integrate and train AI systems.', '#a855f7', 'memory', 'Technical', 160, 100, 5500, 15),
  ('s6', 'DES', 'Design', 'UI/UX and visual content creation.', '#fbbf24', 'palette', 'Creative', 100, 100, 2500, 1),
  ('s7', 'CPY', 'Copywriting', 'Write persuasive and clear marketing content.', '#fb923c', 'history-edu', 'Creative', 90, 100, 2500, 1),
  ('s8', 'VID', 'Video Production', 'Edit and produce professional video content.', '#ef4444', 'videocam', 'Creative', 130, 100, 5500, 15),
  ('s9', 'MKT', 'Marketing', 'Growth strategies and customer acquisition.', '#f43f5e', 'campaign', 'Business', 100, 110, 3500, 5),
  ('s10', 'NEG', 'Negotiation', 'Client deals and pricing strategy.', '#14b8a6', 'handshake', 'Business', 130, 100, 3500, 5),
  ('s11', 'PRJ', 'Project Management', 'Plan and execute workflows efficiently.', '#8b5cf6', 'assignment', 'Business', 110, 100, 3500, 5),
  ('s12', 'FIN', 'Finance', 'Money management and analysis.', '#10b981', 'payments', 'Business', 140, 100, 2500, 10),
  ('s13', 'ENG', 'Professional Writing', 'Clear documentation and communication.', '#f97316', 'translate', 'Communication', 80, 100, 4500, 10),
  ('s14', 'PUB', 'Public Speaking', 'Present ideas and pitch to clients.', '#ec4899', 'record-voice-over', 'Communication', 120, 100, 4500, 10),
  ('s15', 'NET', 'Networking', 'Build professional relationships and clients.', '#22c55e', 'hub', 'Communication', 110, 100, 4500, 10);`,

  `INSERT OR IGNORE INTO clients (id, name, tier, description, reputation_required, perks) VALUES
  ('client_small', 'Small Business', 'small', 'Local small businesses offering minor gigs and opportunities.', 0, '{"perks": ["small_gigs"]}'),
  ('client_medium', 'Medium Business', 'medium', 'Regional businesses with bigger contracts and opportunities.', 50, '{"perks": ["medium_gigs"]}'),
  ('client_startup', 'Startup', 'startup', 'Growing startups offering high-value gigs and special contracts.', 100, '{"perks": ["startup_gigs", "premium_tools"]}'),
  ('client_national', 'National Corporation', 'national', 'Nationwide corporations offering high payment gigs and exclusive projects.', 200, '{"perks": ["national_gigs"]}'),
  ('client_global', 'Global Corporation', 'global', 'International corporations offering premium contracts and top-tier rewards.', 400, '{"perks": ["global_gigs"]}');`,

  `INSERT OR IGNORE INTO tools (id, name, category, sub_category, description, price, perks, required_level, image, base_xp, max_level) VALUES
  ('tool_001','Laptop','Hardware','Computer','Primary device used for completing freelance work.',1000,'{"xp_bonus":5,"gig_speed_bonus":5}',1,'laptop', 100, 20),
  ('tool_002','External Monitor','Hardware','Accessory','Improves multitasking and workflow efficiency.',500,'{"gig_speed_bonus":8,"quality_bonus":5}',2,'external-monitor', 100, 20),
  ('tool_003','Noise Cancelling Headset','Hardware','Audio','Reduces distractions and improves focus.',400,'{"stress_reduction":12}',2,'noise-cancelling-headset', 100, 20),
  ('tool_004','Graphic Tablet','Hardware','Tablet','Essential tool for creative and design projects.',800,'{"quality_bonus":15}',3,'graphic-tablet', 100, 20),
  ('tool_005','Code Editor License','Software','Development','Enhances coding speed and efficiency.',700,'{"gig_speed_bonus":12}',2,'code-editor', 100, 20),
  ('tool_006','Design Software License','Software','Design','Professional design toolkit for high quality output.',900,'{"quality_bonus":18}',2,'design-software', 100, 20),
  ('tool_007','Project Management Tool','Software','Productivity','Organize tasks and increase project success rate.',600,'{"success_bonus":10,"gig_speed_bonus":5}',2,'project-management', 100, 20),
  ('tool_008','AI Assistant','Software','AI','Helps automate tasks and improve output quality.',1500,'{"gig_speed_bonus":10,"quality_bonus":10,"xp_bonus":8}',4,'ai-assistant', 100, 20),
  ('tool_009','Marketing Automation Tool','Software','Marketing','Boosts campaign performance and client acquisition.',1000,'{"success_bonus":15}',3,'marketing-automation', 100, 20),
  ('tool_010','Cloud Storage','Utility','Cloud','Securely store and access files anytime.',500,'{"success_bonus":6,"quality_bonus":4}',1,'cloud-storage', 100, 20),
  ('tool_011','Standing Desk','Office','Furniture','Improves comfort and reduces fatigue.',800,'{"energy_reduction":8,"stress_reduction":5}',2,'standing-desk', 100, 20),
  ('tool_012','Ergonomic Chair','Office','Furniture','Supports long work sessions comfortably.',600,'{"stress_reduction":12}',1,'ergonomic-chair', 100, 20),
  ('tool_013','Desk Lamp','Office','Accessory','Reduces eye strain and improves focus.',200,'{"stress_reduction":5}',1,'desk-lamp', 100, 20),
  ('tool_014','Coffee Machine','Office','Appliance','Provides energy boost during work sessions.',400,'{"energy_reduction":10}',2,'coffee-machine', 100, 20),
  ('tool_015','Air Conditioner','Office','Appliance','Maintains comfortable working environment.',1200,'{"stress_reduction":18}',3,'air-conditioner', 100, 20),
  ('tool_016','Precision Mouse','Hardware','Accessory','Improves accuracy and workflow efficiency.',250,'{"quality_bonus":4,"gig_speed_bonus":3}',1,'precision-mouse', 100, 20),
  ('tool_017','Mechanical Keyboard','Hardware','Accessory','Enhances typing speed and comfort.',300,'{"xp_bonus":4,"gig_speed_bonus":4}',1,'mechanical-keyboard', 100, 20),
  ('tool_018','Webcam','Hardware','Accessory','Improves client communication during meetings.',350,'{"success_bonus":6}',2,'webcam', 100, 20),
  ('tool_019','Antivirus Software','Software','Security','Protects system from threats and data loss.',400,'{"success_bonus":5,"stress_reduction":3}',1,'antivirus', 100, 20),
  ('tool_020','Invoice Generator','Software','Finance','Streamlines billing and payment tracking.',300,'{"success_bonus":6}',1,'invoice-generator', 100, 20),
  ('tool_021','Internet Connection','Utility','Internet','Required for handling online freelance work.',600,'{"gig_speed_bonus":10}',1,'internet', 100, 20),
  ('tool_022','Water Dispenser','Office','Appliance','Keeps you hydrated during long work sessions.',350,'{"energy_reduction":5}',1,'water-dispenser', 100, 20),
  ('tool_023','Foot Rest','Office','Accessory','Improves posture and comfort.',200,'{"stress_reduction":4}',1,'foot-rest', 100, 20),
  ('tool_024','Whiteboard','Office','Accessory','Helps organize ideas and plan tasks visually.',450,'{"xp_bonus":5,"quality_bonus":3}',2,'whiteboard', 100, 20),
  ('tool_025','Mini Fridge','Office','Appliance','Stores snacks and drinks for quick energy boosts.',700,'{"energy_reduction":8}',2,'mini-fridge', 100, 20),
  ('tool_026','Office Plant','Utility','Decoration','Improves workspace mood and reduces stress.',250,'{"stress_reduction":6}',1,'office-plant', 100, 20);`,
];
